package twofactor

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/BladiCreator/go-modular-auth/plugin"
	"github.com/BladiCreator/go-modular-auth/plugins/emailpassword"
)

// PluginID is the unique string identifier for the TwoFactor plugin ("two-factor").
const PluginID = "two-factor"

// Parameter and Result Structs
type (
	// EnableParams defines parameters required to initialize 2FA enrollment for a user.
	EnableParams struct {
		// UserID is the unique identifier of the user enrolling in 2FA (required).
		UserID string `json:"user_id"`

		// Password is the user's current password if password re-authentication is enforced (optional).
		Password string `json:"password,omitempty"`

		// Issuer overrides the default application issuer name shown in authenticator apps (optional).
		Issuer string `json:"issuer,omitempty"`

		// Extra holds dynamic metadata passed through event interceptors (optional).
		Extra map[string]any `json:"extra,omitempty"`
	}

	// EnableResult contains the generated Base32 secret, TOTP setup URI, and initial single-use backup codes.
	EnableResult struct {
		// TOTPURI is the otpauth:// URI encoded with secret, issuer, digits, and period for QR code generation.
		TOTPURI string `json:"totp_uri"`

		// Secret is the generated Base32 encoded secret.
		Secret string `json:"secret"`

		// BackupCodes is the list of generated single-use recovery codes.
		BackupCodes []string `json:"backup_codes"`
	}

	// DisableParams defines parameters to disable 2FA for a user.
	DisableParams struct {
		// UserID identifies the user whose 2FA is being deactivated (required).
		UserID string `json:"user_id"`

		// Password is the optional password confirmation.
		Password string `json:"password,omitempty"`

		// Extra holds dynamic metadata passed through event interceptors (optional).
		Extra map[string]any `json:"extra,omitempty"`
	}

	// GetTOTPURIParams defines parameters to retrieve the TOTP URI for an already configured user.
	GetTOTPURIParams struct {
		// UserID identifies the enrolled user (required).
		UserID string `json:"user_id"`

		// Password is an optional password check.
		Password string `json:"password,omitempty"`
	}

	// VerifyTOTPParams defines parameters to verify an incoming 6- or 8-digit TOTP code.
	VerifyTOTPParams struct {
		// UserID identifies the user submitting the verification code (required).
		UserID string `json:"user_id"`

		// Code is the numeric TOTP code generated by an authenticator application (required).
		Code string `json:"code"`

		// TrustDevice indicates whether the client requests authorizing this device to bypass subsequent 2FA prompts.
		TrustDevice bool `json:"trust_device,omitempty"`

		// DeviceID specifies the unique client hardware/installation identifier required when TrustDevice is true.
		DeviceID string `json:"device_id,omitempty"`

		// Extra holds dynamic metadata passed through event interceptors (optional).
		Extra map[string]any `json:"extra,omitempty"`
	}

	// VerifyBackupCodeParams defines parameters to verify and consume a single-use backup code.
	VerifyBackupCodeParams struct {
		// UserID identifies the user attempting backup code recovery (required).
		UserID string `json:"user_id"`

		// Code is the alphanumeric single-use recovery code (required).
		Code string `json:"code"`

		// Extra holds dynamic metadata passed through event interceptors (optional).
		Extra map[string]any `json:"extra,omitempty"`
	}

	// SendOTPParams defines parameters to trigger an SMS or Email OTP challenge.
	SendOTPParams struct {
		// UserID identifies the user receiving the OTP challenge (required).
		UserID string `json:"user_id"`

		// Extra holds dynamic metadata passed through event interceptors (optional).
		Extra map[string]any `json:"extra,omitempty"`
	}

	// SendOTPResult contains metadata about the dispatched OTP challenge.
	SendOTPResult struct {
		// ExpiresAt specifies the exact timestamp when the dispatched challenge expires.
		ExpiresAt time.Time `json:"expires_at"`
	}

	// VerifyOTPParams defines parameters to verify an active OTP challenge.
	VerifyOTPParams struct {
		// UserID identifies the user submitting the challenge verification code (required).
		UserID string `json:"user_id"`

		// Code is the numeric challenge code delivered to the user (required).
		Code string `json:"code"`

		// Extra holds dynamic metadata passed through event interceptors (optional).
		Extra map[string]any `json:"extra,omitempty"`
	}

	// VerifyResult represents the comprehensive result of any successful 2FA verification.
	VerifyResult struct {
		// Success indicates whether the submitted verification credential was accepted.
		Success bool `json:"success"`

		// UserID is the owner user's identifier.
		UserID string `json:"user_id"`

		// Method specifies the authentication method verified ("totp", "backup_code", "otp").
		Method string `json:"method"`

		// TrustDeviceToken contains the signed device authorization token if TrustDevice was requested and succeeded.
		TrustDeviceToken string `json:"trust_device_token,omitempty"`

		// RemainingCodes reports the count of unconsumed backup recovery codes (populated on backup_code verification).
		RemainingCodes int `json:"remaining_codes,omitempty"`
	}

	// CreateChallengeParams defines parameters to issue a temporary sign-in challenge token.
	CreateChallengeParams struct {
		// UserID identifies the user required to fulfill the 2FA challenge (required).
		UserID string `json:"user_id"`

		// Extra holds dynamic metadata passed through event interceptors (optional).
		Extra map[string]any `json:"extra,omitempty"`
	}

	// ChallengeResult contains the generated challenge token and its expiration.
	ChallengeResult struct {
		// ChallengeToken is the random token string used to complete the multi-factor flow.
		ChallengeToken string `json:"challenge_token"`

		// UserID is the target user's identifier.
		UserID string `json:"user_id"`

		// ExpiresAt is the timestamp when this challenge token becomes invalid.
		ExpiresAt time.Time `json:"expires_at"`
	}

	// VerifyChallengeParams defines parameters to verify a sign-in challenge token using TOTP, Backup Code, or OTP.
	VerifyChallengeParams struct {
		// ChallengeToken is the temporary challenge token issued during sign-in (required).
		ChallengeToken string `json:"challenge_token"`

		// Method specifies the verification method ("totp", "backup_code", "otp") (required).
		Method string `json:"method"`

		// Code is the verification code (TOTP numeric code, backup alphanumeric string, or OTP code) (required).
		Code string `json:"code"`

		// TrustDevice indicates whether to trust this device upon successful verification.
		TrustDevice bool `json:"trust_device,omitempty"`

		// DeviceID specifies the client device identifier.
		DeviceID string `json:"device_id,omitempty"`

		// Extra holds dynamic metadata passed through event interceptors (optional).
		Extra map[string]any `json:"extra,omitempty"`
	}

	// TrustDeviceParams defines parameters to explicitly trust a client device.
	TrustDeviceParams struct {
		// UserID is the owner user identifier (required).
		UserID string `json:"user_id"`

		// DeviceID is the unique client hardware/installation identifier (required).
		DeviceID string `json:"device_id"`
	}

	// TrustDeviceResult contains the issued cryptographic device token and its expiration.
	TrustDeviceResult struct {
		// Token is the signed cryptographic authorization token.
		Token string `json:"token"`

		// ExpiresAt specifies the timestamp after which this device trust expires.
		ExpiresAt time.Time `json:"expires_at"`
	}

	// VerifyTrustDeviceParams defines parameters to test if a device token is currently valid.
	VerifyTrustDeviceParams struct {
		// UserID is the owner user identifier (required).
		UserID string `json:"user_id"`

		// DeviceID is the unique client hardware/installation identifier (required).
		DeviceID string `json:"device_id"`

		// Token is the cryptographic token previously issued to this device (required).
		Token string `json:"token"`
	}

	// RevokeTrustedDeviceParams defines parameters to unauthorize a specific client device.
	RevokeTrustedDeviceParams struct {
		// UserID is the owner user identifier (required).
		UserID string `json:"user_id"`

		// DeviceID is the client hardware/installation identifier to revoke (required).
		DeviceID string `json:"device_id"`
	}

	// GenerateBackupCodesParams defines parameters to regenerate a fresh set of single-use backup codes.
	GenerateBackupCodesParams struct {
		// UserID identifies the user requesting new backup codes (required).
		UserID string `json:"user_id"`

		// Password is an optional password check.
		Password string `json:"password,omitempty"`
	}

	// BackupCodesResult contains the slice of active single-use backup recovery codes.
	BackupCodesResult struct {
		// BackupCodes is the collection of alphanumeric backup recovery codes.
		BackupCodes []string `json:"backup_codes"`
	}

	// ViewBackupCodesParams defines parameters to retrieve active unconsumed backup codes.
	ViewBackupCodesParams struct {
		// UserID identifies the user querying their backup codes (required).
		UserID string `json:"user_id"`
	}
)

// Helper methods for Extra metadata manipulation
func (p *EnableParams) Set(key string, value any) {
	if p.Extra == nil {
		p.Extra = make(map[string]any)
	}
	p.Extra[key] = value
}
func (p *EnableParams) Get(key string) (any, bool) {
	if p.Extra == nil {
		return nil, false
	}
	val, ok := p.Extra[key]
	return val, ok
}

func (p *DisableParams) Set(key string, value any) {
	if p.Extra == nil {
		p.Extra = make(map[string]any)
	}
	p.Extra[key] = value
}
func (p *DisableParams) Get(key string) (any, bool) {
	if p.Extra == nil {
		return nil, false
	}
	val, ok := p.Extra[key]
	return val, ok
}

func (p *VerifyTOTPParams) Set(key string, value any) {
	if p.Extra == nil {
		p.Extra = make(map[string]any)
	}
	p.Extra[key] = value
}
func (p *VerifyTOTPParams) Get(key string) (any, bool) {
	if p.Extra == nil {
		return nil, false
	}
	val, ok := p.Extra[key]
	return val, ok
}

func (p *VerifyBackupCodeParams) Set(key string, value any) {
	if p.Extra == nil {
		p.Extra = make(map[string]any)
	}
	p.Extra[key] = value
}
func (p *VerifyBackupCodeParams) Get(key string) (any, bool) {
	if p.Extra == nil {
		return nil, false
	}
	val, ok := p.Extra[key]
	return val, ok
}

func (p *SendOTPParams) Set(key string, value any) {
	if p.Extra == nil {
		p.Extra = make(map[string]any)
	}
	p.Extra[key] = value
}
func (p *SendOTPParams) Get(key string) (any, bool) {
	if p.Extra == nil {
		return nil, false
	}
	val, ok := p.Extra[key]
	return val, ok
}

func (p *VerifyOTPParams) Set(key string, value any) {
	if p.Extra == nil {
		p.Extra = make(map[string]any)
	}
	p.Extra[key] = value
}
func (p *VerifyOTPParams) Get(key string) (any, bool) {
	if p.Extra == nil {
		return nil, false
	}
	val, ok := p.Extra[key]
	return val, ok
}

func (p *CreateChallengeParams) Set(key string, value any) {
	if p.Extra == nil {
		p.Extra = make(map[string]any)
	}
	p.Extra[key] = value
}
func (p *CreateChallengeParams) Get(key string) (any, bool) {
	if p.Extra == nil {
		return nil, false
	}
	val, ok := p.Extra[key]
	return val, ok
}

func (p *VerifyChallengeParams) Set(key string, value any) {
	if p.Extra == nil {
		p.Extra = make(map[string]any)
	}
	p.Extra[key] = value
}
func (p *VerifyChallengeParams) Get(key string) (any, bool) {
	if p.Extra == nil {
		return nil, false
	}
	val, ok := p.Extra[key]
	return val, ok
}

// Plugin implements pure Go Two-Factor Authentication capabilities.
type Plugin struct {
	repo   Repository
	config Config
	ctx    *plugin.Context
}

// New creates a new TwoFactor plugin instance with the specified repository and functional options.
func New(repo Repository, opts ...Option) *Plugin {
	cfg := DefaultConfig()
	for _, opt := range opts {
		opt(&cfg)
	}
	return &Plugin{
		repo:   repo,
		config: cfg,
	}
}

// ID returns the unique identifier for the TwoFactor plugin ("two-factor").
func (p *Plugin) ID() string {
	return PluginID
}

// Init initializes the plugin within the global GoModularAuth context.
func (p *Plugin) Init(ctx *plugin.Context) error {
	p.ctx = ctx

	// Automatic reaction following a successful email/password sign-in
	p.ctx.Events().Subscribe(emailpassword.EventSignInAfter, func(c context.Context, payload *emailpassword.SignInEventPayload) {
		if payload != nil && payload.User != nil {
			p.ctx.Set(TwoFactorPendingKey(payload.User.ID), true)
		}
	})

	return nil
}

// Enable initializes 2FA enrollment for a user, generating a secure Base32 TOTP secret and recovery backup codes.
func (p *Plugin) Enable(ctx context.Context, params EnableParams) (*EnableResult, error) {
	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventEnableBefore, ctx, &EnableBeforeEventPayload{
			UserID: params.UserID,
			Params: &params,
		})
	}

	secret, err := GenerateBase32Secret(20)
	if err != nil {
		return nil, err
	}

	rawBackupCodes, err := GenerateBackupCodes(p.config.BackupCodeAmount, p.config.BackupCodeLength)
	if err != nil {
		return nil, err
	}

	backupJSON, err := json.Marshal(rawBackupCodes)
	if err != nil {
		return nil, fmt.Errorf("twofactor: failed to encode backup codes: %w", err)
	}

	tf := &TwoFactor{
		UserID:      params.UserID,
		Secret:      secret,
		BackupCodes: string(backupJSON),
		Verified:    p.config.SkipVerificationOnEnable,
		Failures:    0,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}

	existing, _ := p.repo.FindByUserID(ctx, params.UserID)
	if existing != nil {
		tf.ID = existing.ID
		if err := p.repo.Update(ctx, tf); err != nil {
			return nil, err
		}
	} else {
		if err := p.repo.Create(ctx, tf); err != nil {
			return nil, err
		}
	}

	issuer := params.Issuer
	if issuer == "" {
		issuer = p.config.Issuer
	}

	totpURI := BuildTOTPURI(issuer, params.UserID, secret, p.config.TotpDigits, p.config.TotpPeriod, p.config.Algorithm)

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventEnableAfter, ctx, &EnableAfterEventPayload{
			UserID:           params.UserID,
			BackupCodesCount: len(rawBackupCodes),
		})
		p.ctx.Events().Publish(EventTOTPGenerated, ctx, &TOTPGeneratedEventPayload{
			UserID: params.UserID,
			Secret: secret,
		})
	}

	return &EnableResult{
		TOTPURI:     totpURI,
		Secret:      secret,
		BackupCodes: rawBackupCodes,
	}, nil
}

// Disable removes 2FA configuration for the given user, revokes all trusted devices, and deactivates 2FA.
func (p *Plugin) Disable(ctx context.Context, params DisableParams) error {
	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventDisableBefore, ctx, &DisableBeforeEventPayload{
			UserID: params.UserID,
			Params: &params,
		})
	}

	if err := p.repo.DeleteByUserID(ctx, params.UserID); err != nil {
		return err
	}

	_ = p.repo.DeleteTrustDevicesByUserID(ctx, params.UserID)

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventDisableAfter, ctx, &DisableAfterEventPayload{
			UserID: params.UserID,
		})
	}
	return nil
}

// GetTOTPURI retrieves the TOTP setup URI for an already configured user.
func (p *Plugin) GetTOTPURI(ctx context.Context, params GetTOTPURIParams) (string, error) {
	tf, err := p.repo.FindByUserID(ctx, params.UserID)
	if err != nil || tf == nil {
		return "", ErrTwoFactorNotEnabled
	}

	issuer := p.config.Issuer
	totpURI := BuildTOTPURI(issuer, params.UserID, tf.Secret, p.config.TotpDigits, p.config.TotpPeriod, p.config.Algorithm)
	return totpURI, nil
}

// VerifyTOTP validates a user-provided RFC 6238 TOTP code against their stored secret with a ±1 period drift window.
func (p *Plugin) VerifyTOTP(ctx context.Context, params VerifyTOTPParams) (*VerifyResult, error) {
	tf, err := p.repo.FindByUserID(ctx, params.UserID)
	if err != nil || tf == nil {
		return nil, ErrTwoFactorNotEnabled
	}

	if p.isLocked(tf) {
		return nil, ErrAccountLocked
	}

	valid := ValidateTOTPCode(tf.Secret, params.Code, p.config.TotpPeriod, p.config.TotpDigits, p.config.Algorithm)
	if !valid {
		p.recordFailure(ctx, tf, MethodTOTP)
		return nil, ErrInvalidCode
	}

	p.resetFailures(ctx, tf)
	if !tf.Verified {
		tf.Verified = true
		_ = p.repo.Update(ctx, tf)
	}

	var deviceToken string
	if params.TrustDevice && params.DeviceID != "" {
		token, err := p.issueTrustDevice(ctx, params.UserID, params.DeviceID)
		if err == nil {
			deviceToken = token
		}
	}

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventVerifySuccess, ctx, &VerifySuccessEventPayload{
			UserID:      params.UserID,
			Method:      MethodTOTP,
			TrustDevice: params.TrustDevice,
		})
	}

	return &VerifyResult{
		Success:          true,
		UserID:           params.UserID,
		Method:           MethodTOTP,
		TrustDeviceToken: deviceToken,
	}, nil
}

// VerifyBackupCode verifies and atomically consumes a single-use backup recovery code.
func (p *Plugin) VerifyBackupCode(ctx context.Context, params VerifyBackupCodeParams) (*VerifyResult, error) {
	tf, err := p.repo.FindByUserID(ctx, params.UserID)
	if err != nil || tf == nil {
		return nil, ErrTwoFactorNotEnabled
	}

	if p.isLocked(tf) {
		return nil, ErrAccountLocked
	}

	var codes []string
	if err := json.Unmarshal([]byte(tf.BackupCodes), &codes); err != nil {
		return nil, err
	}

	idx, valid := ValidateBackupCode(codes, params.Code)
	if !valid || idx < 0 {
		p.recordFailure(ctx, tf, MethodBackupCode)
		return nil, ErrInvalidCode
	}

	// Atomically consume the matching backup code
	remaining := append(codes[:idx], codes[idx+1:]...)
	updatedJSON, _ := json.Marshal(remaining)
	tf.BackupCodes = string(updatedJSON)

	p.resetFailures(ctx, tf)
	_ = p.repo.Update(ctx, tf)

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventVerifySuccess, ctx, &VerifySuccessEventPayload{
			UserID: params.UserID,
			Method: MethodBackupCode,
		})
	}

	return &VerifyResult{
		Success:        true,
		UserID:         params.UserID,
		Method:         MethodBackupCode,
		RemainingCodes: len(remaining),
	}, nil
}

// GenerateBackupCodes regenerates a fresh set of single-use recovery codes, invalidating prior ones.
func (p *Plugin) GenerateBackupCodes(ctx context.Context, params GenerateBackupCodesParams) (*BackupCodesResult, error) {
	tf, err := p.repo.FindByUserID(ctx, params.UserID)
	if err != nil || tf == nil {
		return nil, ErrTwoFactorNotEnabled
	}

	codes, err := GenerateBackupCodes(p.config.BackupCodeAmount, p.config.BackupCodeLength)
	if err != nil {
		return nil, err
	}

	backupJSON, err := json.Marshal(codes)
	if err != nil {
		return nil, err
	}

	tf.BackupCodes = string(backupJSON)
	tf.UpdatedAt = time.Now()

	if err := p.repo.Update(ctx, tf); err != nil {
		return nil, err
	}

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventBackupCodesRegenerated, ctx, &BackupCodesRegeneratedEventPayload{
			UserID: params.UserID,
			Amount: len(codes),
		})
	}

	return &BackupCodesResult{BackupCodes: codes}, nil
}

// ViewBackupCodes returns the list of active unconsumed single-use backup codes.
func (p *Plugin) ViewBackupCodes(ctx context.Context, params ViewBackupCodesParams) (*BackupCodesResult, error) {
	tf, err := p.repo.FindByUserID(ctx, params.UserID)
	if err != nil || tf == nil {
		return nil, ErrTwoFactorNotEnabled
	}

	var codes []string
	if err := json.Unmarshal([]byte(tf.BackupCodes), &codes); err != nil {
		return nil, err
	}
	return &BackupCodesResult{BackupCodes: codes}, nil
}

// SendOTP generates a short-lived numeric challenge and triggers the registered SendOTP callback and EventBus.
func (p *Plugin) SendOTP(ctx context.Context, params SendOTPParams) (*SendOTPResult, error) {
	if p.config.SendOTP == nil {
		return nil, ErrOTPNotConfigured
	}

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventSendOTPBefore, ctx, &SendOTPBeforeEventPayload{
			UserID: params.UserID,
			Params: &params,
		})
	}

	code, err := GenerateRandomNumericCode(p.config.OTPDigits)
	if err != nil {
		return nil, err
	}

	key := fmt.Sprintf("2fa-otp-%s", params.UserID)
	expiresAt := time.Now().Add(p.config.OTPPeriod)

	challenge := &OTPChallenge{
		Key:       key,
		UserID:    params.UserID,
		CodeHash:  code,
		Attempts:  0,
		ExpiresAt: expiresAt,
	}

	if err := p.repo.SaveOTPChallenge(ctx, challenge); err != nil {
		return nil, err
	}

	if err := p.config.SendOTP(ctx, params.UserID, code); err != nil {
		return nil, err
	}

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventSendOTPAfter, ctx, &SendOTPAfterEventPayload{
			UserID:    params.UserID,
			OTPCode:   code,
			ExpiresAt: expiresAt,
		})
	}

	return &SendOTPResult{ExpiresAt: expiresAt}, nil
}

// VerifyOTP validates a user-submitted code against an active OTP challenge.
func (p *Plugin) VerifyOTP(ctx context.Context, params VerifyOTPParams) (*VerifyResult, error) {
	key := fmt.Sprintf("2fa-otp-%s", params.UserID)
	challenge, err := p.repo.GetOTPChallenge(ctx, key)
	if err != nil || challenge == nil || time.Now().After(challenge.ExpiresAt) {
		return nil, ErrOTPExpired
	}

	if challenge.Attempts >= p.config.Lockout.MaxFailedAttempts {
		_ = p.repo.DeleteOTPChallenge(ctx, key)
		return nil, ErrTooManyAttempts
	}

	if challenge.CodeHash != params.Code {
		challenge.Attempts++
		_ = p.repo.SaveOTPChallenge(ctx, challenge)
		if p.ctx != nil && p.ctx.Events() != nil {
			p.ctx.Events().Publish(EventVerifyFailed, ctx, &VerifyFailedEventPayload{
				UserID:   params.UserID,
				Method:   MethodOTP,
				Failures: challenge.Attempts,
			})
		}
		return nil, ErrInvalidCode
	}

	// Single use: delete on successful verification
	_ = p.repo.DeleteOTPChallenge(ctx, key)

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventVerifySuccess, ctx, &VerifySuccessEventPayload{
			UserID: params.UserID,
			Method: MethodOTP,
		})
	}

	return &VerifyResult{
		Success: true,
		UserID:  params.UserID,
		Method:  MethodOTP,
	}, nil
}

// CreateChallenge generates a short-lived sign-in challenge token following primary credentials verification.
func (p *Plugin) CreateChallenge(ctx context.Context, params CreateChallengeParams) (*ChallengeResult, error) {
	token, err := GenerateRandomToken(32)
	if err != nil {
		return nil, err
	}

	expiresAt := time.Now().Add(p.config.ChallengeExpiry)
	rec := &ChallengeRecord{
		Token:     token,
		UserID:    params.UserID,
		ExpiresAt: expiresAt,
		CreatedAt: time.Now(),
	}

	if err := p.repo.SaveChallenge(ctx, rec); err != nil {
		return nil, err
	}

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventChallengeCreated, ctx, &ChallengeCreatedEventPayload{
			Token:     token,
			UserID:    params.UserID,
			ExpiresAt: expiresAt,
		})
	}

	return &ChallengeResult{
		ChallengeToken: token,
		UserID:         params.UserID,
		ExpiresAt:      expiresAt,
	}, nil
}

// VerifyChallenge validates a sign-in challenge token using the requested method (TOTP, Backup Code, OTP).
func (p *Plugin) VerifyChallenge(ctx context.Context, params VerifyChallengeParams) (*VerifyResult, error) {
	challenge, err := p.repo.GetChallenge(ctx, params.ChallengeToken)
	if err != nil || challenge == nil {
		return nil, ErrInvalidChallengeToken
	}

	if time.Now().After(challenge.ExpiresAt) {
		_ = p.repo.DeleteChallenge(ctx, params.ChallengeToken)
		return nil, ErrChallengeExpired
	}

	var res *VerifyResult
	switch strings.ToLower(params.Method) {
	case MethodTOTP:
		res, err = p.VerifyTOTP(ctx, VerifyTOTPParams{
			UserID:      challenge.UserID,
			Code:        params.Code,
			TrustDevice: params.TrustDevice,
			DeviceID:    params.DeviceID,
			Extra:       params.Extra,
		})
	case MethodBackupCode:
		res, err = p.VerifyBackupCode(ctx, VerifyBackupCodeParams{
			UserID: challenge.UserID,
			Code:   params.Code,
			Extra:  params.Extra,
		})
	case MethodOTP, MethodSMS, MethodEmail:
		res, err = p.VerifyOTP(ctx, VerifyOTPParams{
			UserID: challenge.UserID,
			Code:   params.Code,
			Extra:  params.Extra,
		})
	default:
		return nil, fmt.Errorf("twofactor: unsupported verification method '%s'", params.Method)
	}

	if err != nil {
		return nil, err
	}

	// Consume challenge token upon successful verification
	_ = p.repo.DeleteChallenge(ctx, params.ChallengeToken)

	return res, nil
}

// TrustDevice explicitly authorizes a client device for the configured trust duration.
func (p *Plugin) TrustDevice(ctx context.Context, params TrustDeviceParams) (*TrustDeviceResult, error) {
	if params.UserID == "" || params.DeviceID == "" {
		return nil, fmt.Errorf("twofactor: user_id and device_id are required to trust a device")
	}

	token, err := p.issueTrustDevice(ctx, params.UserID, params.DeviceID)
	if err != nil {
		return nil, err
	}

	expiresAt := time.Now().Add(p.config.TrustDeviceMaxAge)
	return &TrustDeviceResult{
		Token:     token,
		ExpiresAt: expiresAt,
	}, nil
}

// VerifyTrustDevice validates whether an authorized device token is authentic and currently unexpired.
func (p *Plugin) VerifyTrustDevice(ctx context.Context, params VerifyTrustDeviceParams) (bool, error) {
	secret := p.config.TrustDeviceSecret
	if secret == "" {
		secret = "go-modular-auth-default-device-secret"
	}

	validSig := VerifyTrustDeviceToken(params.Token, params.UserID, params.DeviceID, secret)
	if !validSig {
		return false, nil
	}

	rec, err := p.repo.FindTrustDevice(ctx, params.UserID, params.DeviceID)
	if err != nil || rec == nil {
		return false, nil
	}

	if time.Now().After(rec.ExpiresAt) {
		_ = p.repo.DeleteTrustDevice(ctx, params.UserID, params.DeviceID)
		return false, nil
	}

	return true, nil
}

// RevokeTrustedDevice revokes authorization for a single trusted client device.
func (p *Plugin) RevokeTrustedDevice(ctx context.Context, params RevokeTrustedDeviceParams) error {
	return p.repo.DeleteTrustDevice(ctx, params.UserID, params.DeviceID)
}

// RevokeAllTrustedDevices invalidates all authorized devices for the specified user.
func (p *Plugin) RevokeAllTrustedDevices(ctx context.Context, userID string) error {
	return p.repo.DeleteTrustDevicesByUserID(ctx, userID)
}

// Convenience Methods
func (p *Plugin) GenerateTOTPSecret(ctx context.Context, userID string) (string, error) {
	res, err := p.Enable(ctx, EnableParams{UserID: userID})
	if err != nil {
		return "", err
	}
	return res.TOTPURI, nil
}

func (p *Plugin) VerifyCode(ctx context.Context, userID, code string) (bool, error) {
	res, err := p.VerifyTOTP(ctx, VerifyTOTPParams{UserID: userID, Code: code})
	if err != nil {
		return false, err
	}
	return res.Success, nil
}

// Internal Lockout & Security Helpers
func (p *Plugin) isLocked(tf *TwoFactor) bool {
	if tf == nil || !p.config.Lockout.Enabled {
		return false
	}
	if tf.LockedUntil != nil && tf.LockedUntil.After(time.Now()) {
		return true
	}
	return false
}

func (p *Plugin) recordFailure(ctx context.Context, tf *TwoFactor, method string) {
	if tf == nil {
		return
	}
	tf.Failures++
	if p.config.Lockout.Enabled && tf.Failures >= p.config.Lockout.MaxFailedAttempts {
		lockedUntil := time.Now().Add(p.config.Lockout.Duration)
		tf.LockedUntil = &lockedUntil

		if p.ctx != nil && p.ctx.Events() != nil {
			p.ctx.Events().Publish(EventAccountLocked, ctx, &AccountLockedEventPayload{
				UserID:      tf.UserID,
				Failures:    tf.Failures,
				LockedUntil: lockedUntil,
			})
		}
	}
	tf.UpdatedAt = time.Now()
	_ = p.repo.Update(ctx, tf)

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventVerifyFailed, ctx, &VerifyFailedEventPayload{
			UserID:   tf.UserID,
			Method:   method,
			Failures: tf.Failures,
		})
	}
}

func (p *Plugin) resetFailures(ctx context.Context, tf *TwoFactor) {
	if tf == nil {
		return
	}
	if tf.Failures > 0 || tf.LockedUntil != nil {
		tf.Failures = 0
		tf.LockedUntil = nil
		tf.UpdatedAt = time.Now()
		_ = p.repo.Update(ctx, tf)
	}
}

func (p *Plugin) issueTrustDevice(ctx context.Context, userID, deviceID string) (string, error) {
	secret := p.config.TrustDeviceSecret
	if secret == "" {
		secret = "go-modular-auth-default-device-secret"
	}

	expiresAt := time.Now().Add(p.config.TrustDeviceMaxAge)
	token := GenerateTrustDeviceToken(userID, deviceID, secret, expiresAt)

	rec := &TrustDeviceRecord{
		ID:        fmt.Sprintf("td_%s_%s", userID, deviceID),
		UserID:    userID,
		DeviceID:  deviceID,
		TokenHash: token,
		ExpiresAt: expiresAt,
		CreatedAt: time.Now(),
	}

	if err := p.repo.SaveTrustDevice(ctx, rec); err != nil {
		return "", err
	}

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventDeviceTrusted, ctx, &DeviceTrustedEventPayload{
			UserID:    userID,
			DeviceID:  deviceID,
			ExpiresAt: expiresAt,
		})
	}

	return token, nil
}
