package twofactor

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha1"
	"encoding/base32"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"math/big"
	"net/url"
	"strings"
	"time"

	"github.com/BladiCreator/go-modular-auth/plugin"
	"github.com/BladiCreator/go-modular-auth/plugins/emailpassword"
)

// PluginID is the unique string identifier for the TwoFactor plugin ("two-factor").
const PluginID = "two-factor"

// Parameter and Result Structs
type (
	// EnableParams defines parameters required to initialize 2FA enrollment for a user.
	EnableParams struct {
		// UserID is the unique identifier of the user enrolling in 2FA (required).
		UserID string `json:"user_id"`

		// Password is the user's current password if password re-authentication is enforced (optional).
		Password string `json:"password,omitempty"`

		// Issuer overrides the default application issuer name shown in authenticator apps (optional).
		Issuer string `json:"issuer,omitempty"`

		// Extra holds dynamic metadata passed through event interceptors (optional).
		Extra map[string]any `json:"extra,omitempty"`
	}

	// EnableResult contains the generated TOTP setup URI and initial single-use backup codes.
	EnableResult struct {
		// TOTPURI is the otpauth:// URI encoded with secret, issuer, digits, and period for QR code generation.
		TOTPURI string `json:"totp_uri"`

		// BackupCodes is the list of generated single-use recovery codes.
		BackupCodes []string `json:"backup_codes"`
	}

	// DisableParams defines parameters to disable 2FA for a user.
	DisableParams struct {
		// UserID identifies the user whose 2FA is being deactivated (required).
		UserID string `json:"user_id"`

		// Password is the optional password confirmation.
		Password string `json:"password,omitempty"`

		// Extra holds dynamic metadata passed through event interceptors (optional).
		Extra map[string]any `json:"extra,omitempty"`
	}

	// GetTOTPURIParams defines parameters to retrieve the TOTP URI for an already configured user.
	GetTOTPURIParams struct {
		// UserID identifies the enrolled user (required).
		UserID string `json:"user_id"`

		// Password is an optional password check.
		Password string `json:"password,omitempty"`
	}

	// VerifyTOTPParams defines parameters to verify an incoming 6- or 8-digit TOTP code.
	VerifyTOTPParams struct {
		// UserID identifies the user submitting the verification code (required).
		UserID string `json:"user_id"`

		// Code is the numeric TOTP code generated by an authenticator application (required).
		Code string `json:"code"`
	}

	// GenerateBackupCodesParams defines parameters to regenerate a fresh set of single-use backup codes.
	GenerateBackupCodesParams struct {
		// UserID identifies the user requesting new backup codes (required).
		UserID string `json:"user_id"`

		// Password is an optional password check.
		Password string `json:"password,omitempty"`
	}

	// VerifyBackupCodeParams defines parameters to verify and consume a single-use backup code.
	VerifyBackupCodeParams struct {
		// UserID identifies the user attempting backup code recovery (required).
		UserID string `json:"user_id"`

		// Code is the alphanumeric single-use recovery code (required).
		Code string `json:"code"`
	}

	// SendOTPParams defines parameters to trigger an SMS or Email OTP challenge.
	SendOTPParams struct {
		// UserID identifies the user receiving the OTP challenge (required).
		UserID string `json:"user_id"`
	}

	// VerifyOTPParams defines parameters to verify an active OTP challenge.
	VerifyOTPParams struct {
		// UserID identifies the user submitting the challenge verification code (required).
		UserID string `json:"user_id"`

		// Code is the numeric challenge code delivered to the user (required).
		Code string `json:"code"`
	}

	// ViewBackupCodesParams defines parameters to retrieve active unconsumed backup codes.
	ViewBackupCodesParams struct {
		// UserID identifies the user querying their backup codes (required).
		UserID string `json:"user_id"`
	}
)

// Set allows event interceptor plugins to attach dynamic metadata to the enrollment request.
func (p *EnableParams) Set(key string, value any) {
	if p.Extra == nil {
		p.Extra = make(map[string]any)
	}
	p.Extra[key] = value
}

// Get retrieves a dynamic metadata value attached to the enrollment request.
func (p *EnableParams) Get(key string) (any, bool) {
	if p.Extra == nil {
		return nil, false
	}
	val, ok := p.Extra[key]
	return val, ok
}

// Plugin implements Two-Factor Authentication capabilities.
type Plugin struct {
	repo   Repository
	config Config
	ctx    *plugin.Context
}

// New creates a new TwoFactor plugin instance with the specified repository and functional options.
//
// Arguments:
//   - repo: Implementation of twofactor.Repository interface.
//   - opts: Optional functional configuration options (WithIssuer, WithTOTPOptions, WithBackupCodeOptions, etc.).
//
// Returns:
//   - *Plugin: The configured TwoFactor plugin instance.
func New(repo Repository, opts ...Option) *Plugin {
	cfg := DefaultConfig()
	for _, opt := range opts {
		opt(&cfg)
	}
	return &Plugin{
		repo:   repo,
		config: cfg,
	}
}

// ID returns the unique identifier for the TwoFactor plugin ("two-factor").
func (p *Plugin) ID() string {
	return PluginID
}

// Init initializes the plugin within the global GoModularAuth context.
func (p *Plugin) Init(ctx *plugin.Context) error {
	p.ctx = ctx

	// Automatic reaction following a successful email/password sign-in
	p.ctx.Events().Subscribe(emailpassword.EventSignInAfter, func(c context.Context, payload *emailpassword.SignInEventPayload) {
		if payload != nil && payload.User != nil {
			p.ctx.Set(TwoFactorPendingKey(payload.User.ID), true)
		}
	})

	return nil
}

// Enable enables 2FA enrollment for a user, generates a secure Base32 TOTP secret and backup codes,
// persists the TwoFactor record, and returns the TOTP URI alongside unconsumed recovery codes.
//
// Brief Explanation:
//
//	Generates a cryptographically random 20-byte secret encoded in Base32, creates the configured amount of
//	alphanumeric backup recovery codes, stores the TwoFactor entity in the repository, and publishes
//	EventEnableTwoFactorBefore, EventEnableTwoFactorAfter, and EventTOTPGenerated.
//
// Function:
//
//	Initial step for enrolling a user in Two-Factor Authentication.
//
// Arguments:
//   - ctx: Request cancellation context.
//   - params: EnableParams containing UserID, optional Password, Issuer, and dynamic Extra metadata.
//
// Returns:
//   - *EnableResult: Contains the otpauth:// URI for QR display and the slice of single-use backup codes.
//   - error: Database failure error if persistence fails.
//
// Example:
//
//	res, err := tfPlugin.Enable(ctx, twofactor.EnableParams{
//		UserID: "usr_12345",
//		Issuer: "Enterprise Cloud",
//	})
//	if err != nil {
//		log.Fatalf("Enable 2FA failed: %v", err)
//	}
//	fmt.Printf("Scan QR Code URI: %s\n", res.TOTPURI)
//	fmt.Printf("Save your backup codes: %v\n", res.BackupCodes)
func (p *Plugin) Enable(ctx context.Context, params EnableParams) (*EnableResult, error) {
	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventEnableTwoFactorBefore, ctx, &EnableTwoFactorBeforeEventPayload{
			UserID: params.UserID,
			Params: &params,
		})
	}

	// Generate 20-byte random secret for Base32 encoding
	secretBytes := make([]byte, 20)
	if _, err := rand.Read(secretBytes); err != nil {
		return nil, err
	}
	secret := base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(secretBytes)

	// Generate backup codes
	rawBackupCodes, err := p.generateBackupCodesList()
	if err != nil {
		return nil, err
	}

	backupJSON, err := json.Marshal(rawBackupCodes)
	if err != nil {
		return nil, fmt.Errorf("twofactor: failed to encode backup codes: %w", err)
	}

	tf := &TwoFactor{
		UserID:      params.UserID,
		Secret:      secret,
		BackupCodes: string(backupJSON),
		Verified:    p.config.SkipVerificationOnEnable,
		Failures:    0,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}

	existing, _ := p.repo.FindByUserID(ctx, params.UserID)
	if existing != nil {
		tf.ID = existing.ID
		if err := p.repo.Update(ctx, tf); err != nil {
			return nil, err
		}
	} else {
		if err := p.repo.Create(ctx, tf); err != nil {
			return nil, err
		}
	}

	issuer := params.Issuer
	if issuer == "" {
		issuer = p.config.Issuer
	}

	totpURI := fmt.Sprintf("otpauth://totp/%s:%s?secret=%s&issuer=%s&digits=%d&period=%d",
		url.PathEscape(issuer),
		url.PathEscape(params.UserID),
		secret,
		url.QueryEscape(issuer),
		p.config.TotpDigits,
		p.config.TotpPeriod,
	)

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventEnableTwoFactorAfter, ctx, &EnableTwoFactorAfterEventPayload{
			UserID:           params.UserID,
			BackupCodesCount: len(rawBackupCodes),
		})
		p.ctx.Events().Publish(EventTOTPGenerated, ctx, &TOTPGeneratedEventPayload{
			UserID: params.UserID,
			Secret: secret,
		})
	}

	return &EnableResult{
		TOTPURI:     totpURI,
		BackupCodes: rawBackupCodes,
	}, nil
}

// Disable removes 2FA configuration for the given user, effectively deactivating two-factor enforcement.
//
// Brief Explanation:
//
//	Deletes the user's TwoFactor record from storage and emits EventDisableTwoFactorBefore and EventDisableTwoFactorAfter.
//
// Function:
//
//	Deactivates MFA for a user account.
//
// Arguments:
//   - ctx: Request cancellation context.
//   - params: DisableParams containing UserID and optional Password.
//
// Returns:
//   - error: Nil on success, or database error on failure.
//
// Example:
//
//	err := tfPlugin.Disable(ctx, twofactor.DisableParams{
//		UserID: "usr_12345",
//	})
//	if err != nil {
//		log.Fatalf("Disable 2FA failed: %v", err)
//	}
func (p *Plugin) Disable(ctx context.Context, params DisableParams) error {
	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventDisableTwoFactorBefore, ctx, &DisableTwoFactorEventPayload{
			UserID: params.UserID,
		})
	}

	if err := p.repo.DeleteByUserID(ctx, params.UserID); err != nil {
		return err
	}

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventDisableTwoFactorAfter, ctx, &DisableTwoFactorEventPayload{
			UserID: params.UserID,
		})
	}
	return nil
}

// GetTOTPURI retrieves the TOTP setup URI for an already configured user.
//
// Brief Explanation:
//
//	Looks up the user's stored Base32 secret and reconstructs the otpauth:// URI for re-display in settings.
//
// Function:
//
//	Retrieves QR code URI for existing 2FA users.
//
// Arguments:
//   - ctx: Request cancellation context.
//   - params: GetTOTPURIParams containing UserID.
//
// Returns:
//   - string: The full otpauth:// URI string.
//   - error: ErrTwoFactorNotEnabled if user has not enrolled in 2FA.
//
// Example:
//
//	uri, err := tfPlugin.GetTOTPURI(ctx, twofactor.GetTOTPURIParams{
//		UserID: "usr_12345",
//	})
func (p *Plugin) GetTOTPURI(ctx context.Context, params GetTOTPURIParams) (string, error) {
	tf, err := p.repo.FindByUserID(ctx, params.UserID)
	if err != nil || tf == nil {
		return "", ErrTwoFactorNotEnabled
	}

	totpURI := fmt.Sprintf("otpauth://totp/%s:%s?secret=%s&issuer=%s&digits=%d&period=%d",
		url.PathEscape(p.config.Issuer),
		url.PathEscape(params.UserID),
		tf.Secret,
		url.QueryEscape(p.config.Issuer),
		p.config.TotpDigits,
		p.config.TotpPeriod,
	)

	return totpURI, nil
}

// VerifyTOTP validates a user-provided RFC 6238 TOTP code against their stored secret with a ±1 period drift window.
//
// Brief Explanation:
//
//	Checks if the user account is locked due to rate limiting, calculates HMAC-SHA1 codes across the tolerance
//	window (t-period, t, t+period), increments failure count on mismatch (locking account if limit reached),
//	resets failures on success, marks 2FA as verified, and emits EventVerifyTOTPBefore and EventVerifyTOTPAfter.
//
// Function:
//
//	Primary second-factor verification step during login or sensitive operations.
//
// Arguments:
//   - ctx: Request cancellation context.
//   - params: VerifyTOTPParams containing UserID and the numeric Code string.
//
// Returns:
//   - bool: True if the code matches.
//   - error: ErrTwoFactorNotEnabled, ErrAccountLocked, ErrInvalidCode, or database error.
//
// Example:
//
//	ok, err := tfPlugin.VerifyTOTP(ctx, twofactor.VerifyTOTPParams{
//		UserID: "usr_12345",
//		Code:   "482910",
//	})
//	if err != nil {
//		log.Fatalf("Verification rejected: %v", err)
//	}
//	fmt.Printf("2FA Verification Successful: %t\n", ok)
func (p *Plugin) VerifyTOTP(ctx context.Context, params VerifyTOTPParams) (bool, error) {
	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventVerifyTOTPBefore, ctx, &VerifyTOTPBeforeEventPayload{
			UserID: params.UserID,
		})
	}

	tf, err := p.repo.FindByUserID(ctx, params.UserID)
	if err != nil || tf == nil {
		return false, ErrTwoFactorNotEnabled
	}

	if p.isLocked(tf) {
		return false, ErrAccountLocked
	}

	valid := p.validateTOTPCode(tf.Secret, params.Code)
	if !valid {
		p.recordFailure(ctx, tf)
		if p.ctx != nil && p.ctx.Events() != nil {
			p.ctx.Events().Publish(EventVerifyTOTPAfter, ctx, &VerifyTOTPAfterEventPayload{
				UserID:  params.UserID,
				Success: false,
			})
		}
		return false, ErrInvalidCode
	}

	p.resetFailures(ctx, tf)
	if !tf.Verified {
		tf.Verified = true
		_ = p.repo.Update(ctx, tf)
	}

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventVerifyTOTPAfter, ctx, &VerifyTOTPAfterEventPayload{
			UserID:  params.UserID,
			Success: true,
		})
	}
	return true, nil
}

// GenerateBackupCodes regenerates a fresh set of single-use recovery codes, overwriting any previous codes.
//
// Brief Explanation:
//
//	Generates new alphanumeric codes according to BackupCodeAmount and BackupCodeLength, serializes them to JSON,
//	and saves the updated TwoFactor record.
//
// Function:
//
//	Allows users to regenerate recovery codes when running low or following a security reset.
//
// Arguments:
//   - ctx: Request cancellation context.
//   - params: GenerateBackupCodesParams containing UserID and optional Password.
//
// Returns:
//   - []string: The slice of freshly generated single-use backup codes.
//   - error: ErrTwoFactorNotEnabled or database error.
//
// Example:
//
//	codes, err := tfPlugin.GenerateBackupCodes(ctx, twofactor.GenerateBackupCodesParams{
//		UserID: "usr_12345",
//	})
func (p *Plugin) GenerateBackupCodes(ctx context.Context, params GenerateBackupCodesParams) ([]string, error) {
	tf, err := p.repo.FindByUserID(ctx, params.UserID)
	if err != nil || tf == nil {
		return nil, ErrTwoFactorNotEnabled
	}

	codes, err := p.generateBackupCodesList()
	if err != nil {
		return nil, err
	}

	backupJSON, err := json.Marshal(codes)
	if err != nil {
		return nil, err
	}

	tf.BackupCodes = string(backupJSON)
	tf.UpdatedAt = time.Now()

	if err := p.repo.Update(ctx, tf); err != nil {
		return nil, err
	}

	return codes, nil
}

// VerifyBackupCode verifies and atomically consumes a single-use backup code.
//
// Brief Explanation:
//
//	Validates the user's recovery code (case-insensitive, ignoring hyphens), removes the used code from
//	storage so it cannot be reused, resets failure counters, and emits EventVerifyBackupCodeAfter with the
//	number of remaining backup codes.
//
// Function:
//
//	Account recovery when an authenticator device is lost.
//
// Arguments:
//   - ctx: Request cancellation context.
//   - params: VerifyBackupCodeParams containing UserID and Code.
//
// Returns:
//   - bool: True if the backup code was valid and successfully consumed.
//   - error: ErrTwoFactorNotEnabled, ErrAccountLocked, ErrInvalidCode, or database error.
//
// Example:
//
//	ok, err := tfPlugin.VerifyBackupCode(ctx, twofactor.VerifyBackupCodeParams{
//		UserID: "usr_12345",
//		Code:   "AB87-C192",
//	})
//	if err != nil {
//		log.Fatalf("Backup code invalid: %v", err)
//	}
func (p *Plugin) VerifyBackupCode(ctx context.Context, params VerifyBackupCodeParams) (bool, error) {
	tf, err := p.repo.FindByUserID(ctx, params.UserID)
	if err != nil || tf == nil {
		return false, ErrTwoFactorNotEnabled
	}

	if p.isLocked(tf) {
		return false, ErrAccountLocked
	}

	var codes []string
	if err := json.Unmarshal([]byte(tf.BackupCodes), &codes); err != nil {
		return false, err
	}

	foundIdx := -1
	normalizedInput := strings.ToUpper(strings.ReplaceAll(params.Code, "-", ""))
	for i, c := range codes {
		normalizedStored := strings.ToUpper(strings.ReplaceAll(c, "-", ""))
		if normalizedStored == normalizedInput {
			foundIdx = i
			break
		}
	}

	if foundIdx == -1 {
		p.recordFailure(ctx, tf)
		if p.ctx != nil && p.ctx.Events() != nil {
			p.ctx.Events().Publish(EventVerifyBackupCodeAfter, ctx, &VerifyBackupCodeAfterEventPayload{
				UserID:         params.UserID,
				Success:        false,
				RemainingCodes: len(codes),
			})
		}
		return false, ErrInvalidCode
	}

	// Atomically consume the backup code
	remaining := append(codes[:foundIdx], codes[foundIdx+1:]...)
	updatedJSON, _ := json.Marshal(remaining)
	tf.BackupCodes = string(updatedJSON)

	p.resetFailures(ctx, tf)
	_ = p.repo.Update(ctx, tf)

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventVerifyBackupCodeAfter, ctx, &VerifyBackupCodeAfterEventPayload{
			UserID:         params.UserID,
			Success:        true,
			RemainingCodes: len(remaining),
		})
	}
	return true, nil
}

// ViewBackupCodes returns the list of active unconsumed single-use backup codes.
//
// Brief Explanation:
//
//	Retrieves and parses the user's TwoFactor backup codes array from storage.
//
// Function:
//
//	Allows authenticated users to view their remaining recovery codes in profile security settings.
//
// Arguments:
//   - ctx: Request cancellation context.
//   - params: ViewBackupCodesParams containing UserID.
//
// Returns:
//   - []string: The slice of remaining active backup codes.
//   - error: ErrTwoFactorNotEnabled or database error.
//
// Example:
//
//	codes, err := tfPlugin.ViewBackupCodes(ctx, twofactor.ViewBackupCodesParams{
//		UserID: "usr_12345",
//	})
func (p *Plugin) ViewBackupCodes(ctx context.Context, params ViewBackupCodesParams) ([]string, error) {
	tf, err := p.repo.FindByUserID(ctx, params.UserID)
	if err != nil || tf == nil {
		return nil, ErrTwoFactorNotEnabled
	}

	var codes []string
	if err := json.Unmarshal([]byte(tf.BackupCodes), &codes); err != nil {
		return nil, err
	}
	return codes, nil
}

// SendOTP generates a short-lived numeric challenge and triggers the registered SendOTP delivery callback (SMS/Email).
//
// Brief Explanation:
//
//	Generates a cryptographically secure random numeric string of length OTPDigits, persists an OTPChallenge record
//	with an expiration timestamp, calls the user's SendOTP callback, and publishes EventSendOTPBefore and EventSendOTPAfter.
//
// Function:
//
//	Out-of-band challenge-based 2FA (e.g. SMS code or Email verification).
//
// Arguments:
//   - ctx: Request cancellation context.
//   - params: SendOTPParams containing UserID.
//
// Returns:
//   - error: ErrOTPNotConfigured if no SendOTP callback was configured, or delivery error.
//
// Example:
//
//	err := tfPlugin.SendOTP(ctx, twofactor.SendOTPParams{
//		UserID: "usr_12345",
//	})
func (p *Plugin) SendOTP(ctx context.Context, params SendOTPParams) error {
	if p.config.SendOTP == nil {
		return ErrOTPNotConfigured
	}

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventSendOTPBefore, ctx, &SendOTPBeforeEventPayload{
			UserID: params.UserID,
		})
	}

	maxVal := int64(1)
	for i := 0; i < p.config.OTPDigits; i++ {
		maxVal *= 10
	}
	n, err := rand.Int(rand.Reader, big.NewInt(maxVal))
	if err != nil {
		return err
	}
	code := fmt.Sprintf("%0*d", p.config.OTPDigits, n.Int64())

	key := fmt.Sprintf("2fa-otp-%s", params.UserID)
	expiresAt := time.Now().Add(p.config.OTPPeriod)

	challenge := &OTPChallenge{
		Key:       key,
		UserID:    params.UserID,
		CodeHash:  code,
		Attempts:  0,
		ExpiresAt: expiresAt,
	}

	if err := p.repo.SaveOTPChallenge(ctx, challenge); err != nil {
		return err
	}

	if err := p.config.SendOTP(ctx, params.UserID, code); err != nil {
		return err
	}

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventSendOTPAfter, ctx, &SendOTPAfterEventPayload{
			UserID:    params.UserID,
			ExpiresAt: expiresAt,
		})
	}
	return nil
}

// VerifyOTP validates a user-submitted code against an active OTP challenge.
//
// Brief Explanation:
//
//	Retrieves the stored challenge, checks expiration and maximum attempt thresholds, validates equality,
//	deletes the challenge on success (enforcing single use), or increments attempt counters on failure.
//	Emits EventVerifyOTPAfter.
//
// Function:
//
//	Validates temporary challenge codes delivered out-of-band.
//
// Arguments:
//   - ctx: Request cancellation context.
//   - params: VerifyOTPParams containing UserID and Code.
//
// Returns:
//   - bool: True if verification succeeds.
//   - error: ErrOTPExpired, ErrTooManyAttempts, ErrInvalidCode, or database error.
//
// Example:
//
//	ok, err := tfPlugin.VerifyOTP(ctx, twofactor.VerifyOTPParams{
//		UserID: "usr_12345",
//		Code:   "938102",
//	})
func (p *Plugin) VerifyOTP(ctx context.Context, params VerifyOTPParams) (bool, error) {
	key := fmt.Sprintf("2fa-otp-%s", params.UserID)
	challenge, err := p.repo.GetOTPChallenge(ctx, key)
	if err != nil || challenge == nil || time.Now().After(challenge.ExpiresAt) {
		return false, ErrOTPExpired
	}

	if challenge.Attempts >= p.config.MaxAllowedAttempts {
		_ = p.repo.DeleteOTPChallenge(ctx, key)
		return false, ErrTooManyAttempts
	}

	if challenge.CodeHash != params.Code {
		challenge.Attempts++
		_ = p.repo.SaveOTPChallenge(ctx, challenge)
		if p.ctx != nil && p.ctx.Events() != nil {
			p.ctx.Events().Publish(EventVerifyOTPAfter, ctx, &VerifyOTPAfterEventPayload{
				UserID:  params.UserID,
				Success: false,
			})
		}
		return false, ErrInvalidCode
	}

	// Single use: delete on successful verification
	_ = p.repo.DeleteOTPChallenge(ctx, key)

	if p.ctx != nil && p.ctx.Events() != nil {
		p.ctx.Events().Publish(EventVerifyOTPAfter, ctx, &VerifyOTPAfterEventPayload{
			UserID:  params.UserID,
			Success: true,
		})
	}
	return true, nil
}

// GenerateTOTPSecret provides a convenience wrapper for simple TOTP secret generation, returning the setup URI.
func (p *Plugin) GenerateTOTPSecret(ctx context.Context, userID string) (string, error) {
	res, err := p.Enable(ctx, EnableParams{UserID: userID})
	if err != nil {
		return "", err
	}
	return res.TOTPURI, nil
}

// VerifyCode provides a convenience wrapper for simple TOTP code validation.
func (p *Plugin) VerifyCode(ctx context.Context, userID, code string) (bool, error) {
	return p.VerifyTOTP(ctx, VerifyTOTPParams{UserID: userID, Code: code})
}

// Internal TOTP and Security Helpers
func (p *Plugin) generateBackupCodesList() ([]string, error) {
	codes := make([]string, p.config.BackupCodeAmount)
	const charset = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
	charsetLen := big.NewInt(int64(len(charset)))

	for i := 0; i < p.config.BackupCodeAmount; i++ {
		b := make([]byte, p.config.BackupCodeLength)
		for j := range b {
			idx, err := rand.Int(rand.Reader, charsetLen)
			if err != nil {
				return nil, err
			}
			b[j] = charset[idx.Int64()]
		}
		raw := string(b)
		mid := len(raw) / 2
		codes[i] = fmt.Sprintf("%s-%s", raw[:mid], raw[mid:])
	}
	return codes, nil
}

func (p *Plugin) validateTOTPCode(secret string, code string) bool {
	if code == "" || secret == "" {
		return false
	}

	secretBytes, err := base32.StdEncoding.WithPadding(base32.NoPadding).DecodeString(strings.ToUpper(secret))
	if err != nil {
		return false
	}

	period := int64(p.config.TotpPeriod)
	if period <= 0 {
		period = 30
	}

	now := time.Now().Unix()

	// Tolerance window +/- 1 period
	for t := now - period; t <= now+period; t += period {
		counter := uint64(t / period)
		buf := make([]byte, 8)
		binary.BigEndian.PutUint64(buf, counter)

		mac := hmac.New(sha1.New, secretBytes)
		mac.Write(buf)
		sum := mac.Sum(nil)

		offset := sum[len(sum)-1] & 0xf
		binCode := (int32(sum[offset]&0x7f) << 24) |
			(int32(sum[offset+1]&0xff) << 16) |
			(int32(sum[offset+2]&0xff) << 8) |
			(int32(sum[offset+3] & 0xff))

		mod := int32(1)
		for i := 0; i < p.config.TotpDigits; i++ {
			mod *= 10
		}

		calcCode := fmt.Sprintf("%0*d", p.config.TotpDigits, binCode%mod)
		if calcCode == code {
			return true
		}
	}
	return false
}

func (p *Plugin) isLocked(tf *TwoFactor) bool {
	if tf == nil {
		return false
	}
	if tf.LockedUntil != nil && tf.LockedUntil.After(time.Now()) {
		return true
	}
	return false
}

func (p *Plugin) recordFailure(ctx context.Context, tf *TwoFactor) {
	if tf == nil {
		return
	}
	tf.Failures++
	if tf.Failures >= p.config.MaxAllowedAttempts {
		lockedUntil := time.Now().Add(p.config.LockoutDuration)
		tf.LockedUntil = &lockedUntil
	}
	tf.UpdatedAt = time.Now()
	_ = p.repo.Update(ctx, tf)
}

func (p *Plugin) resetFailures(ctx context.Context, tf *TwoFactor) {
	if tf == nil {
		return
	}
	if tf.Failures > 0 || tf.LockedUntil != nil {
		tf.Failures = 0
		tf.LockedUntil = nil
		tf.UpdatedAt = time.Now()
		_ = p.repo.Update(ctx, tf)
	}
}
