package twofactor

import (
	"time"

	"github.com/BladiCreator/go-modular-auth/plugin"
)

type (
	// EnableParams defines parameters required to enable 2FA for a user.
	EnableParams struct {
		// UserID is the unique identifier of the user enrolling in 2FA (required).
		UserID string `json:"user_id"`

		// Password is the user's current password if password re-authentication is enforced (optional).
		Password string `json:"password,omitempty"`

		// Issuer overrides the default application issuer name shown in authenticator apps (optional).
		Issuer string `json:"issuer,omitempty"`

		plugin.ExtraContainer
	}

	// EnableResult contains the generated Base32 secret, TOTP setup URI, and initial single-use backup codes.
	EnableResult struct {
		// TOTPURI is the otpauth:// URI encoded with secret, issuer, digits, and period for QR code generation.
		TOTPURI string `json:"totp_uri"`

		// Secret is the generated Base32 encoded secret.
		Secret string `json:"secret"`

		// BackupCodes is the list of generated single-use recovery codes.
		BackupCodes []string `json:"backup_codes"`
	}

	// DisableParams defines parameters to disable 2FA for a user.
	DisableParams struct {
		// UserID identifies the user whose 2FA is being deactivated (required).
		UserID string `json:"user_id"`

		// Password is the optional password confirmation.
		Password string `json:"password,omitempty"`

		plugin.ExtraContainer
	}

	// GetTOTPURIParams defines parameters to retrieve the TOTP URI for an already configured user.
	GetTOTPURIParams struct {
		// UserID identifies the enrolled user (required).
		UserID string `json:"user_id"`

		// Password is an optional password check.
		Password string `json:"password,omitempty"`

		plugin.ExtraContainer
	}

	// VerifyTOTPParams defines parameters to verify an incoming 6- or 8-digit TOTP code.
	VerifyTOTPParams struct {
		// UserID identifies the user submitting the verification code (required).
		UserID string `json:"user_id"`

		// Code is the numeric TOTP code generated by an authenticator application (required).
		Code string `json:"code"`

		// TrustDevice indicates whether the client requests authorizing this device to bypass subsequent 2FA prompts.
		TrustDevice bool `json:"trust_device,omitempty"`

		// DeviceID specifies the unique client hardware/installation identifier required when TrustDevice is true.
		DeviceID string `json:"device_id,omitempty"`

		plugin.ExtraContainer
	}

	// VerifyBackupCodeParams defines parameters to verify and consume a single-use backup code.
	VerifyBackupCodeParams struct {
		// UserID identifies the user attempting backup code recovery (required).
		UserID string `json:"user_id"`

		// Code is the alphanumeric single-use recovery code (required).
		Code string `json:"code"`

		plugin.ExtraContainer
	}

	// SendOTPParams defines parameters to trigger an SMS or Email OTP challenge.
	SendOTPParams struct {
		// UserID identifies the user receiving the OTP challenge (required).
		UserID string `json:"user_id"`

		plugin.ExtraContainer
	}

	// SendOTPResult contains metadata about the dispatched OTP challenge.
	SendOTPResult struct {
		// ExpiresAt specifies the exact timestamp when the dispatched challenge expires.
		ExpiresAt time.Time `json:"expires_at"`
	}

	// VerifyOTPParams defines parameters to verify an active OTP challenge.
	VerifyOTPParams struct {
		// UserID identifies the user submitting the challenge verification code (required).
		UserID string `json:"user_id"`

		// Code is the numeric challenge code delivered to the user (required).
		Code string `json:"code"`

		plugin.ExtraContainer
	}

	// VerifyResult represents the comprehensive result of any successful 2FA verification.
	VerifyResult struct {
		// Success indicates whether the submitted verification credential was accepted.
		Success bool `json:"success"`

		// UserID is the owner user's identifier.
		UserID string `json:"user_id"`

		// Method specifies the authentication method verified ("totp", "backup_code", "otp").
		Method string `json:"method"`

		// TrustDeviceToken contains the signed device authorization token if TrustDevice was requested and succeeded.
		TrustDeviceToken string `json:"trust_device_token,omitempty"`

		// RemainingCodes reports the count of unconsumed backup recovery codes (populated on backup_code verification).
		RemainingCodes int `json:"remaining_codes,omitempty"`
	}

	// CreateChallengeParams defines parameters to issue a temporary sign-in challenge token.
	CreateChallengeParams struct {
		// UserID identifies the user required to fulfill the 2FA challenge (required).
		UserID string `json:"user_id"`

		plugin.ExtraContainer
	}

	// ChallengeResult contains the generated challenge token and its expiration.
	ChallengeResult struct {
		// ChallengeToken is the random token string used to complete the multi-factor flow.
		ChallengeToken string `json:"challenge_token"`

		// UserID is the target user's identifier.
		UserID string `json:"user_id"`

		// ExpiresAt is the timestamp when this challenge token becomes invalid.
		ExpiresAt time.Time `json:"expires_at"`
	}

	// VerifyChallengeParams defines parameters to verify a sign-in challenge token using TOTP, Backup Code, or OTP.
	VerifyChallengeParams struct {
		// ChallengeToken is the temporary challenge token issued during sign-in (required).
		ChallengeToken string `json:"challenge_token"`

		// Method specifies the verification method ("totp", "backup_code", "otp") (required).
		Method string `json:"method"`

		// Code is the verification code (TOTP numeric code, backup alphanumeric string, or OTP code) (required).
		Code string `json:"code"`

		// TrustDevice indicates whether to trust this device upon successful verification.
		TrustDevice bool `json:"trust_device,omitempty"`

		// DeviceID specifies the client device identifier.
		DeviceID string `json:"device_id,omitempty"`

		plugin.ExtraContainer
	}

	// TrustDeviceParams defines parameters to explicitly trust a client device.
	TrustDeviceParams struct {
		// UserID is the owner user identifier (required).
		UserID string `json:"user_id"`

		// DeviceID is the unique client hardware/installation identifier (required).
		DeviceID string `json:"device_id"`

		plugin.ExtraContainer
	}

	// TrustDeviceResult contains the issued cryptographic device token and its expiration.
	TrustDeviceResult struct {
		// Token is the signed cryptographic authorization token.
		Token string `json:"token"`

		// ExpiresAt specifies the timestamp after which this device trust expires.
		ExpiresAt time.Time `json:"expires_at"`
	}

	// VerifyTrustDeviceParams defines parameters to test if a device token is currently valid.
	VerifyTrustDeviceParams struct {
		// UserID is the owner user identifier (required).
		UserID string `json:"user_id"`

		// DeviceID is the unique client hardware/installation identifier (required).
		DeviceID string `json:"device_id"`

		// Token is the cryptographic token previously issued to this device (required).
		Token string `json:"token"`

		plugin.ExtraContainer
	}

	// RevokeTrustedDeviceParams defines parameters to unauthorize a specific client device.
	RevokeTrustedDeviceParams struct {
		// UserID is the owner user identifier (required).
		UserID string `json:"user_id"`

		// DeviceID is the client hardware/installation identifier to revoke (required).
		DeviceID string `json:"device_id"`

		plugin.ExtraContainer
	}

	// GenerateBackupCodesParams defines parameters to regenerate a fresh set of single-use backup codes.
	GenerateBackupCodesParams struct {
		// UserID identifies the user requesting new backup codes (required).
		UserID string `json:"user_id"`

		// Password is an optional password check.
		Password string `json:"password,omitempty"`

		plugin.ExtraContainer
	}

	// BackupCodesResult contains the slice of active single-use backup recovery codes.
	BackupCodesResult struct {
		// BackupCodes is the collection of alphanumeric backup recovery codes.
		BackupCodes []string `json:"backup_codes"`
	}

	// ViewBackupCodesParams defines parameters to retrieve active unconsumed backup codes.
	ViewBackupCodesParams struct {
		// UserID identifies the user querying their backup codes (required).
		UserID string `json:"user_id"`

		plugin.ExtraContainer
	}
)
